version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  alertmanager-data:

services:
  webhook:
    container_name: webhookServer
    image: node:18
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/home/node/app
    ports:
      - "5555:5555"
    expose:
      - "5555"
    command: "npm start"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.yml:/etc/prometheus/alert.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: nodeExporter
    pid: host
    restart: unless-stopped
    expose:
      - "9100"
    ports:
      - "9100:9100"
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    expose:
      - "8080"
  blackbox:
    container_name: blackBox
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox/blackbox.yml
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"

  alertmanager:
    container_name: alertManager
    image: prom/alertmanager:latest
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./config:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 3030:8080

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=1529164
      - MYSQL_DATABASE=kien
      - MYSQL_USER=kien
      - MYSQL_PASSWORD=1529164

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=kien
     - POSTGRES_PASSWORD=1529164
