global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']
#--------------------------------------
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100','host.docker.internal:9100','10.0.206.96:9100']
#--------------------------------------
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
#--------------------------------------
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - https://www.google.com.vn/?hl=vi
        - https://apec.com.vn
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.206.96:9115  # The blackbox exporter's real hostname:port.
#----------------------------------------
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ '10.0.206.96:9093' ]
rule_files:
      - "alert.yml"
