global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
#--------------------------------------
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.1.3:9100']
#--------------------------------------
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
#--------------------------------------
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://apec.com.vn
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.3:9115  # The blackbox exporter's real hostname:port.
#----------------------------------------
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ '192.168.1.3:9093' ]
rule_files:
      - "alert.yml"
