apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://10.0.206.37:9090 #host computer ip. If not replace with http://host.docker.internal:9090
    isDefault: true
    editable: true
